### ISSUE TITLE
Line follower's code 

### ISSUE THREAD

**Issue by Tarekmohamed97** [Tarekmohamed97/ASUMobiCarG37#5]
كل واحد يبدا يكتب و يشتغل على كود العربية كامل ...لازم كله يشتغل فيه و يكتبه بنفسه او على الاقل يجيب كود جاهز يحطه عنده على برنامج الاردوينو و يبدا يفهم كل حاجة فيه ....لازم كله يبقى فاهمه علشان لما حد يعمل تعديل يبقى فاهم بيعمل ايه .....فى مصادر كتير هتلاقيه بمجرد ماتكتب اسم المشروع 
RC Car line follower's code 
Sensors required for the first phase (easy driving ) : 
Ultrasonic (to avoid obstacles .... this is for phase one ) 

deadline : at most saturday 3/3/2018 
good luck

**Comment by abdosabry** [comment]
تمام انا هبدا من النهارده isa

**Comment by amlsalama** [comment]
تمام هبدء فيه

**Comment by abdosabry** [comment]
انا رفعت الكود 😄💪
