### ISSUE TITLE
h bridge with transistor !!

### ISSUE THREAD

**Issue by tahaa255** [Tarekmohamed97/ASUMobiCarG37#6]
i guess using h bridge with transistor is bad idea as it produce low current that not enough for full speed motor , so using motor drive IC is the best idea right now ..... any suggestion !!
![screenshot 151](https://user-images.githubusercontent.com/36480266/36699776-692182ba-1b56-11e8-867b-7bf0739dd796.jpg)

**Comment by amlsalama** [comment]
i agree m3ak bs i don't have any suggestions at the moment h search 3leh
